
CREATE TABLE Users (
  ID int NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR (50) UNIQUE NOT NULL,
  EMAIL VARCHAR (100) UNIQUE NOT NULL,
  HASH VARBINARY (255) NOT NULL,
  SALT VARBINARY (255) NOT NULL,
  TOKEN VARCHAR (255) NOT NULL,
  ENABLE BOOLEAN,
  PRIMARY KEY (ID)
) COMMENT='this is USER table';

CREATE TABLE Tasks(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR (50) NOT NULL,
  TASK VARCHAR (255) NOT NULL,
  STATUS BIT NOT NULL,
  ID_USER INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_USER) REFERENCES Users(ID)
) COMMENT='this is TASKS table';
